# 파이썬 기초이해

In [1]:
print(int(True))
print(int(False))

1
0


In [2]:
print?

In [3]:
print([1,2,3] *2) #리스트와 연산은 문자열과 같다고 생각하자. 그만큼 반복하겠다는 얘기
print([1,2,3] *0)

[1, 2, 3, 1, 2, 3]
[]


## numpy 기초이해

In [5]:
import numpy as np

print(np.array([1,2,3]) *2) # 생각하는 1*2 / 2*2 / 3*2 연산이 만들어짐
print(np.array([1,2,3]) *0)

[2 4 6]
[0 0 0]


In [7]:
print(np.array([[1,2],[1,3],[1,4]]) * np.array([1,10]) ) #행렬 곱

[[ 1 20]
 [ 1 30]
 [ 1 40]]
