### 난수 발생

+ 파이썬 내장 random 모듈보다 더 빠르게 많은 난수 표본 데이타를 생성

+ 적합한 난수는 시뮬레이션의 결과에 영향을 미치기에 중요함


[ ex ] 시뮬레이션의 난수 발생

침대 매트릭스의 충격완화 시뮬레이션을 한다고 할 때 1번 실험에 공을 50번을 던진다면 힘의 세기를 0~1 단위라고 할 때 임의의 힘의 세기로 50번 던졌을 때 평균 강도를 구할 수 있는데, 이 때 임의의 수 난수 발생을 numpy를 이용한다.
그러나 기본 패키지의 random 함수를 이용하지 않고 numpy을 이용하는 이유는 numpy가 속도도 빠르고 더 세밀하게 난수를 발생시킨다.



####  numpy의 난수 발생 함수의 차이를 조사하세요


    1) np.random.random([n, m])

    2) np.random.normal(size=( n, m))

    3) np.random.randn(n,m)

    4) np.random.rand(n,m)
    
    5) np.random.randint(n, m)
    
 

In [1]:
import numpy as np

np.random.random([3, 4])

array([[0.96694528, 0.39541743, 0.5719864 , 0.20568113],
       [0.3539649 , 0.78631799, 0.96867859, 0.86038012],
       [0.17085188, 0.71276692, 0.01269293, 0.38860375]])

In [2]:
arr2 = np.random.normal(size=(3,4))
arr2 #정규분포에 의하여 뽑아주는 랜덤수

array([[-0.29397723,  0.79584549, -0.95907273, -0.9946922 ],
       [-0.43626039, -0.5886309 ,  1.8448181 ,  0.02046772],
       [-0.46037818, -0.37184547,  0.1562229 , -1.22321065]])

In [44]:
arr2 = np.random.normall((3,4)) #mistake
arr2

array([3.5136884 , 4.45142617])

In [45]:
arr3 = np.random.randn(3,4) #실수
arr3

array([[-0.28012605,  0.60698876, -1.52821139, -2.04266524],
       [ 0.59484882,  0.30676555, -1.77802459, -0.01061151],
       [-0.83148671,  0.16749708, -0.06063069, -1.67556308]])

In [46]:
arr4 = np.random.rand(3,4) #양수만 나옴
arr4

array([[0.33065395, 0.98600306, 0.38242555, 0.27691448],
       [0.19327693, 0.16842392, 0.03805503, 0.1148873 ],
       [0.1808067 , 0.14306771, 0.204505  , 0.36399307]])

### [참고] 

+ random	: 0.0에서 1.0 사이의 난수 추출

+ rand	: 균등분포에서 표준 추출

+ randint	: 최소, 최대 범위내에서 임의의 난수 추출

+ randn	: 표준편차 1, 평균값 0인 정규분포에서 표준 추출

+ normal	: 정규분포에서 표준추출

+ shuffle	: 리스트나 배열의 순서를 뒤섞음


### [참고]


NumPy의 random 서브패키지에는 난수를 생성하는 다양한 명령을 제공한다. 그 중 가장 간단하고 많이 사용되는 것은 다음 3가지 명령이다.


•	rand: 0부터 1사이의 균일 분포

•	randn: 가우시안 표준 정규 분포

•	randint: 균일 분포의 정수 난수

rand 명령은 0부터 1사이에서 균일한 확률 분포로 실수 난수를 생성한다. 숫자 인수는 생성할 난수의 크기이다. 여러개의 인수를 넣으면 해당 크기를 가진 행렬을 생성한다.

### [참고] 데이타 사이언스 스쿨 

[파이썬 > 난수 발생과 카운팅](https://datascienceschool.net/01%20python/03.05%20%EB%82%9C%EC%88%98%20%EB%B0%9C%EC%83%9D%EA%B3%BC%20%EC%B9%B4%EC%9A%B4%ED%8C%85.html?highlight=%EB%82%9C%EC%88%98%20%EB%B0%9C%EC%83%9D%EA%B3%BC%20%EC%B9%B4%EC%9A%B4%ED%8C%85)