### 행렬의 정렬

1. np.sort() : 넘파이에서 sort() 호출

2. np.array.sort() : 행렬자체에서 sort() 호출


####  두 방식 sort() 함수의 차이점


1. np.sort() : 원 행렬을 그대로 유지한채 원 행렬의 정렬된 행렬을 반환

2. np.array.sort() : 원 행렬 자체를 정렬한 형태로 변환하며 None을 반환

In [2]:
import numpy as np

origin = np.array([3,1,9,7])
print('원본:', origin)

원본: [3 1 9 7]


In [3]:
# 넘파이 sort
sorted1 = np.sort(origin)
print('원본 :',origin)
print('정렬 후 :',sorted1)

원본 : [3 1 9 7]
정렬 후 : [1 3 7 9]


In [4]:
# 행렬의 sort
sorted2 = origin.sort()
print('원본 :',origin)
print('정렬 후 :',sorted2)

원본 : [1 3 7 9]
정렬 후 : None


### 내림차순 정렬 [::-1]

In [10]:
sorted1 [::-1] #거꾸로내림차순정렬



array([9, 7, 3, 1])

### 2차원 이상의 행렬에서  np.sort() 이해하기

- axis=0 : 행방향 -> 열단위
- axis=1 : 열방향 -> 행단위

In [11]:
arr = np.array([[9, 6, 3],[5, 11, 2]])


print(arr)


row_sort = np.sort(arr, axis=0)
print(row_sort)


row_sort = np.sort(arr, axis=1)
print(row_sort)


[[ 9  6  3]
 [ 5 11  2]]
[[ 5  6  2]
 [ 9 11  3]]
[[ 3  6  9]
 [ 2  5 11]]


In [12]:
?np.sort

####  정렬된 행렬의 인덱스 반환 : argsort()

In [15]:
arr = np.array([3, 8, 2, 5])
sorted = np.sort(arr)
print(sorted)

idx = np.argsort(arr)
print(idx) #정렬한 배열의 인덱스 값

[2 3 5 8]
[2 0 3 1]
